import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSession } from "next-auth/react"
import { useEffect } from "react"
import { Store } from '../src/components/Store'
import { Login } from "../src/components/LoginButton";
import { useRouter } from 'next/router'
import { NavBar } from '../src/components/NavBar'

export default function Home() {
  const { data: session } = useSession()
  const router = useRouter()

  useEffect(() => {
    console.log(session)
  }, [session])

  console.log({ session })

  // if (session)
  //   router.push('/games')

  return (
    <div className={styles.container}>
      <Head>
        <title>Play Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Store />
    </div>
  )
}
